version: '3'

services:
    db:
        platform: linux/x86_64
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"

    web:
        build: 
            context: .
            dockerfile: Dockerfile_back
        # environment:
        #     - 'API_KEY_TW = 04ctqlivqIjNGRP8awg1vBogT'
        #     - 'API_KEY_TW_SECRET = cigo6abMyYT9lYH2ZGeIKr5pBWWNS1MRXQZbEwGYkRlwFSz9Zy'
        env_file: development.env
        command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/myapp
            - ./app/vendor/bundle:/myapp/vendor/bundle
        ports:
            - 3000:3000
        depends_on:
            - db

    front:
        build: 
            context: ./frontend
            dockerfile: Dockerfile_front
        volumes:
            - ./frontend:/frontend
        command: /bin/sh -c "cd frontend && yarn && yarn start"
        ports:
            - 8000:3000
